# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import voice_plugin_v1_pb2 as voice__plugin__v1__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in voice_plugin_v1_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VoicePluginStub:
    """---------- 服务定义 ----------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Handshake = channel.unary_unary(
                '/voice_plugin.v1.VoicePlugin/Handshake',
                request_serializer=voice__plugin__v1__pb2.HandshakeRequest.SerializeToString,
                response_deserializer=voice__plugin__v1__pb2.HandshakeResponse.FromString,
                _registered_method=True)
        self.Configure = channel.unary_unary(
                '/voice_plugin.v1.VoicePlugin/Configure',
                request_serializer=voice__plugin__v1__pb2.ConfigRequest.SerializeToString,
                response_deserializer=voice__plugin__v1__pb2.Empty.FromString,
                _registered_method=True)
        self.LoadModel = channel.unary_unary(
                '/voice_plugin.v1.VoicePlugin/LoadModel',
                request_serializer=voice__plugin__v1__pb2.LoadModelRequest.SerializeToString,
                response_deserializer=voice__plugin__v1__pb2.LoadModelResponse.FromString,
                _registered_method=True)
        self.Interrupt = channel.unary_unary(
                '/voice_plugin.v1.VoicePlugin/Interrupt',
                request_serializer=voice__plugin__v1__pb2.InterruptRequest.SerializeToString,
                response_deserializer=voice__plugin__v1__pb2.InterruptResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/voice_plugin.v1.VoicePlugin/Health',
                request_serializer=voice__plugin__v1__pb2.Empty.SerializeToString,
                response_deserializer=voice__plugin__v1__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/voice_plugin.v1.VoicePlugin/Shutdown',
                request_serializer=voice__plugin__v1__pb2.Empty.SerializeToString,
                response_deserializer=voice__plugin__v1__pb2.Empty.FromString,
                _registered_method=True)
        self.Process = channel.stream_stream(
                '/voice_plugin.v1.VoicePlugin/Process',
                request_serializer=voice__plugin__v1__pb2.PluginMessage.SerializeToString,
                response_deserializer=voice__plugin__v1__pb2.PluginMessage.FromString,
                _registered_method=True)


class VoicePluginServicer:
    """---------- 服务定义 ----------
    """

    def Handshake(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Configure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Interrupt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Process(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoicePluginServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Handshake': grpc.unary_unary_rpc_method_handler(
                    servicer.Handshake,
                    request_deserializer=voice__plugin__v1__pb2.HandshakeRequest.FromString,
                    response_serializer=voice__plugin__v1__pb2.HandshakeResponse.SerializeToString,
            ),
            'Configure': grpc.unary_unary_rpc_method_handler(
                    servicer.Configure,
                    request_deserializer=voice__plugin__v1__pb2.ConfigRequest.FromString,
                    response_serializer=voice__plugin__v1__pb2.Empty.SerializeToString,
            ),
            'LoadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadModel,
                    request_deserializer=voice__plugin__v1__pb2.LoadModelRequest.FromString,
                    response_serializer=voice__plugin__v1__pb2.LoadModelResponse.SerializeToString,
            ),
            'Interrupt': grpc.unary_unary_rpc_method_handler(
                    servicer.Interrupt,
                    request_deserializer=voice__plugin__v1__pb2.InterruptRequest.FromString,
                    response_serializer=voice__plugin__v1__pb2.InterruptResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=voice__plugin__v1__pb2.Empty.FromString,
                    response_serializer=voice__plugin__v1__pb2.HealthResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=voice__plugin__v1__pb2.Empty.FromString,
                    response_serializer=voice__plugin__v1__pb2.Empty.SerializeToString,
            ),
            'Process': grpc.stream_stream_rpc_method_handler(
                    servicer.Process,
                    request_deserializer=voice__plugin__v1__pb2.PluginMessage.FromString,
                    response_serializer=voice__plugin__v1__pb2.PluginMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'voice_plugin.v1.VoicePlugin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('voice_plugin.v1.VoicePlugin', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VoicePlugin:
    """---------- 服务定义 ----------
    """

    @staticmethod
    def Handshake(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voice_plugin.v1.VoicePlugin/Handshake',
            voice__plugin__v1__pb2.HandshakeRequest.SerializeToString,
            voice__plugin__v1__pb2.HandshakeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Configure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voice_plugin.v1.VoicePlugin/Configure',
            voice__plugin__v1__pb2.ConfigRequest.SerializeToString,
            voice__plugin__v1__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voice_plugin.v1.VoicePlugin/LoadModel',
            voice__plugin__v1__pb2.LoadModelRequest.SerializeToString,
            voice__plugin__v1__pb2.LoadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Interrupt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voice_plugin.v1.VoicePlugin/Interrupt',
            voice__plugin__v1__pb2.InterruptRequest.SerializeToString,
            voice__plugin__v1__pb2.InterruptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voice_plugin.v1.VoicePlugin/Health',
            voice__plugin__v1__pb2.Empty.SerializeToString,
            voice__plugin__v1__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voice_plugin.v1.VoicePlugin/Shutdown',
            voice__plugin__v1__pb2.Empty.SerializeToString,
            voice__plugin__v1__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Process(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/voice_plugin.v1.VoicePlugin/Process',
            voice__plugin__v1__pb2.PluginMessage.SerializeToString,
            voice__plugin__v1__pb2.PluginMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
